Traceback (most recent call last):
  File "/Users/joreilly/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/joreilly/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/joreilly/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/joreilly/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/joreilly/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/joreilly/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/joreilly/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/joreilly/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#first, create a new (empty) column
movies['UK_classification'] = 'None'

# np.isin to do a boolean check on every element of the array and see if it is in a different list (your list of interest)
# use np.where to get booleans where that condition is met, assign a new value if true, or do nothing if not true
movies['UK_classification'] = np.where(np.isin(movies.Certificate, ['G', 'TV-G', 'TV-Y', 'TV-7']), 'U', movies.classification)
movies['UK_classification'] = np.where(np.isin(movies.Certificate, ['PG', 'TV-PG']), 'PG', movies.classification)


#the syntax for this is:
# np.where(set condition, do this if condition is met, otherwise do this)
# np.isin(array_to_test, list of values you want to check if the element matches)

#so the code is doing:
# finding where the movie certificate is either G, TV-G, TV-Y or TV-7
# setting the value of 'classification' to 'U' if that movie meets the condition
# if not, it sets the value of 'classification' to itself (i.e. it does nothing)



------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/q4/twg1yll54y142rc02m5wwbt40000gr/T/ipykernel_34726/367159761.py[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0;31m# np.isin to do a boolean check on every element of the array and see if it is in a different list (your list of interest)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;31m# use np.where to get booleans where that condition is met, assign a new value if true, or do nothing if not true[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0mmovies[0m[0;34m[[0m[0;34m'UK_classification'[0m[0;34m][0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mwhere[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0misin[0m[0;34m([0m[0mmovies[0m[0;34m.[0m[0mCertificate[0m[0;34m,[0m [0;34m[[0m[0;34m'G'[0m[0;34m,[0m [0;34m'TV-G'[0m[0;34m,[0m [0;34m'TV-Y'[0m[0;34m,[0m [0;34m'TV-7'[0m[0;34m][0m[0;34m)[0m[0;34m,[0m [0;34m'U'[0m[0;34m,[0m [0mmovies[0m[0;34m.[0m[0mclassification[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0mmovies[0m[0;34m[[0m[0;34m'UK_classification'[0m[0;34m][0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mwhere[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0misin[0m[0;34m([0m[0mmovies[0m[0;34m.[0m[0mCertificate[0m[0;34m,[0m [0;34m[[0m[0;34m'PG'[0m[0;34m,[0m [0;34m'TV-PG'[0m[0;34m][0m[0;34m)[0m[0;34m,[0m [0;34m'PG'[0m[0;34m,[0m [0mmovies[0m[0;34m.[0m[0mclassification[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py[0m in [0;36m__getattr__[0;34m(self, name)[0m
[1;32m   5573[0m         ):
[1;32m   5574[0m             [0;32mreturn[0m [0mself[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5575[0;31m         [0;32mreturn[0m [0mobject[0m[0;34m.[0m[0m__getattribute__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   5576[0m [0;34m[0m[0m
[1;32m   5577[0m     [0;32mdef[0m [0m__setattr__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m:[0m [0mstr[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m [0;34m->[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'DataFrame' object has no attribute 'classification'
AttributeError: 'DataFrame' object has no attribute 'classification'

